on: 
  push:
    branches: 
      - main
      - feature/*

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Azure Login via OIDC
      uses: azure/login@v2.3.0
      with: 
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Create terraform.tfvars file
      run: |
        cat <<EOF > dev/infra/terraform.tfvars
        client_id       = "${{ secrets.AZURE_CLIENT_ID }}"
        client_secret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
        tenant_id       = "${{ secrets.AZURE_TENANT_ID }}"
        subscription_id = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        EOF

    - name: Terraform Init
      run: terraform init
      working-directory: dev/infra

    - name: Terraform Validate
      run: terraform validate
      working-directory: dev/infra

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
      working-directory: dev/infra

  terraform-apply:
    needs: terraform-init-plan
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Azure Login via OIDC
      uses: azure/login@v2.3.0
      with: 
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Create terraform.tfvars file
      run: |
        cat <<EOF > dev/infra/terraform.tfvars
        client_id       = "${{ secrets.AZURE_CLIENT_ID }}"
        client_secret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
        tenant_id       = "${{ secrets.AZURE_TENANT_ID }}"
        subscription_id = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        EOF

    - name: Terraform Init
      run: terraform init
      working-directory: dev/infra

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
      working-directory: dev/infra
