on: 
  push:
    branches: 
      - main
      - feature/*

permissions:
  id-token: write
  contents: read

jobs: 
  terraformInitJob:
    name: Build Stage
    runs-on: self-hosted
    steps:
    
    - name: Checkout
      uses: actions/checkout@v5.0.0
      
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        version: 1.13.0
        
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: d6ba5d46-ddc3-48a6-8ee4-4fead81c2c76
        tenant-id: b24a5be3-6852-43c6-b00e-086d16b535ab
        subscription-id: 258a8e61-bb4a-4a2e-99d2-ca7211e4a421
        
    - name: Terraform Init
      id: init
      run: terraform init -input=false
      working-directory: infra
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: infra
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
      working-directory: infra
