on: 
  push:
    branches: 
      - main
      - feature/*

jobs: 
  terraformInitJob:
    name: My first Job
    runs-on: self-hosted
    steps:
    - name: Terraform installer
      uses: autero1/action-terraform@v3.0.1
      with:
        version: 1.13.0
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: # optional
        tenant-id: # optional
        subscription-id: # optional
        enable-AzPSSession: # optiona
        environment: # optional, default is azurecloud
        allow-no-subscriptions: # optional
        audience: # optional, default is api://AzureADTokenExchange
        auth-type: # optional, default is SERVICE_PRINCIPAL
          
          
    - name: Terraform Init
      id: init
      run: terraform init -input=false
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
    # - name: Terraform Plan
    #   id: plan
    #   run: terraform plan -no-color -input=false
    #   continue-on-error: true
