on: 
  push:
    branches: 
      - main
      - feature/*

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Azure Login via OIDC (Hardcoded IDs)
      uses: azure/login@v2.3.0
      with: 
        client-id: d6ba5d46-ddc3-48a6-8ee4-4fead81c2c76
        tenant-id: b24a5be3-6852-43c6-b00e-086d16b535ab
        subscription-id: 258a8e61-bb4a-4a2e-99d2-ca7211e4a421
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init 
      working-directory: dev/infra 

    - name: Terraform Validate
      run: terraform validate
      working-directory: dev/infra
    
    - name: Terraform Plan
      run: terraform plan 
      continue-on-error: true
      working-directory: dev/infra

  terraform-apply:
    needs: terraform-init-plan
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Azure Login via OIDC (Hardcoded IDs)
      uses: azure/login@v2.3.0
      with: 
        client-id: d6ba5d46-ddc3-48a6-8ee4-4fead81c2c76
        tenant-id: b24a5be3-6852-43c6-b00e-086d16b535ab
        subscription-id: 258a8e61-bb4a-4a2e-99d2-ca7211e4a421

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init
      working-directory: dev/infra

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: dev/infra
