on: 
  push:
    branches: 
      - main
      - feature/*

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Azure Login via OIDC
      uses: azure/login@v2.3.0
      with: 
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init 
      working-directory: dev/infra 

    - name: Terraform Validate
      run: terraform validate
      working-directory: dev/infra
    
    - name: Terraform Plan
      run: terraform plan 
      continue-on-error: true
      working-directory: dev/infra

  terraform-apply:
    needs: terraform-init-plan
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Azure Login via OIDC
      uses: azure/login@v2.3.0
      with: 
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init
      working-directory: dev/infra

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: dev/infra
